persistence false
log_dest stdout

# Listener para MQTT estandar (1883)
listener 1883 0.0.0.0
allow_anonymous true

# Listener para WebSockets (9001) - Por si lo necesitas en el futuro
listener 9001 0.0.0.0
protocol websockets
